<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3P9qenW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3P9qenW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3P9qenW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3P9qenW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3P9qenW\App_KernelDevDebugContainer([
    'container.build_hash' => '3P9qenW',
    'container.build_id' => 'f55b8247',
    'container.build_time' => 1619515099,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3P9qenW');
